services:
  app_myhttp:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.myhttp
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_MYHTTP_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MYHTTP_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MYHTTP_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5960:8080
